### ISSUE TITLE
Possibility of adding Karakalpak language?

### ISSUE THREAD

**Issue by atabekm** [IS2AI/TurkicTTS#3]
Hi,

I was wondering if we can add Karakalpak language to this project? Given that Karakalpak language is pretty close to Kazakh, I think in theory it should work. If I create a pull request with changes in `ipa_convert.py`, would that be a good starting point? Thanks.

**Comment by yeshpanovrustem** [comment]
Hello, Atabek.

Thank you for your interest in contributing to our project and for considering the addition of the Karakalpak language. I appreciate your initiative in proposing changes to `ipa_convert.py`.
Unfortunately, I am currently tied up with several ongoing projects and commitments, and I will not be able to dedicate time to integrating the Karakalpak language into the project at this time.
However, please feel free to use the existing codes and mapping in the repository as you see fit. Your contributions are valuable, and we are glad that our project can be of use to you.

**Comment by atabekm** [comment]
Thanks Rustem for prompt reply. I will try to look for more simple solutions to start with, looks like TatarTTS might the one.

**Comment by yeshpanovrustem** [comment]
Sure. Nice meeting you. TatarTTS (https://github.com/IS2AI/TatarTTS). Good luck!
